# Generated by Django 4.2.6 on 2023-10-08 14:30

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('is_predefined', models.BooleanField(default=False)),
                ('category_name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('is_predefined', models.BooleanField(default=False)),
                ('category_name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('is_income', models.BooleanField(default=False)),
                ('money_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('expense_category', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_expenses_no_category), to='core.expensecategory')),
                ('income_category', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_incomes_no_category), to='core.incomecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('money_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.budget')),
                ('category_id', models.ForeignKey(on_delete=models.SET(core.models.get_expenses_no_category), to='core.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='AccountStatement',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
