# Generated by Django 4.2.6 on 2023-10-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_accountstatement_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetcategory',
            old_name='budget_id',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='budgetcategory',
            old_name='category_id',
            new_name='category',
        ),
    ]
